// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CHIRI_KoreanParticles","status":true,"description":"받침 유무에 따라 자동으로 한국어 조사를 처리합니다. 자세한 사용법은 도움말을 확인해 주세요.","parameters":{}},
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"EnemyBook","status":true,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"??????"}},
{"name":"ItemBook","status":true,"description":"Displays detailed statuses of items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type"}},
{"name":"SimpleMsgSideView","status":true,"description":"at sideview battle, only display item/skill names.","parameters":{"displayAttack":"0","position":"1"}},
{"name":"TitleCommandPosition","status":true,"description":"Changes the position of the title command window.","parameters":{"Offset X":"0","Offset Y":"0","Width":"240","Background":"0"}},
{"name":"WeaponSkill","status":true,"description":"Change skill id of attack for each weapon.","parameters":{}},
{"name":"ScreenResolution","status":true,"description":"v1.00 Change your game's screen resolution to your liking!","parameters":{"Screen Width":"816","Screen Height":"459"}},
{"name":"RS_HUD_4m","status":true,"description":"This plugin draws the HUD, which displays the hp and mp and exp\nand level of each party members. (v1.0.7)","parameters":{"Width":"317","Height":"101","Margin":"0","Gaussian Blur":"true","Show":"true","Opacity":"255","Anchor":"LeftTop","Arrangement":"['LeftTop', 'LeftBottom', 'RightTop', 'RightBottom']","preloadImportantFaces":"['Actor1', 'Actor2', 'Actor3']","Battle Only":"true"}},
{"name":"RS_HUD_4m_InBattle","status":true,"description":"This plugin draws the Battle HUD (Addon v1.1.0)","parameters":{"Width":"317","Height":"100","Margin":"0","Show":"true","Opacity":"255","Anchor":"LeftTop","Arrangement":"['LeftTop', 'LeftBottom', 'RightTop', 'RightBottom']"}}
];
